changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Conversion quality
      labels: [conversion-quality]
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Documentation and maintenance
      labels: ['*']
