const DEFAULT_REPOSITORY = 'zwhy149/bead-grid-studio';
const API_ROOT = 'https://api.github.com';
const API_VERSION = '2022-11-28';
const PER_PAGE = 100;

function repositoryFromArguments() {
  const candidate = process.argv[2] || process.env.GITHUB_REPOSITORY || DEFAULT_REPOSITORY;
  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(candidate)) {
    throw new Error(`Invalid repository "${candidate}". Use OWNER/REPOSITORY.`);
  }
  return candidate;
}

function requestHeaders() {
  const headers = {
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': API_VERSION,
    'User-Agent': 'bead-grid-studio-repo-metrics',
  };
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  return headers;
}

function rateLimitDetails(response) {
  const remaining = response.headers.get('x-ratelimit-remaining');
  const resetValue = Number(response.headers.get('x-ratelimit-reset'));
  const reset = Number.isFinite(resetValue) && resetValue > 0
    ? new Date(resetValue * 1000).toLocaleString()
    : 'unknown';
  return `remaining=${remaining ?? 'unknown'}, reset=${reset}`;
}

async function github(path) {
  const response = await fetch(`${API_ROOT}${path}`, { headers: requestHeaders() });
  if (!response.ok) {
    let message = '';
    try {
      message = (await response.json()).message || '';
    } catch {
      message = await response.text();
    }
    const limitHint = response.status === 403 || response.status === 429
      ? ` GitHub API rate limit: ${rateLimitDetails(response)}. Set GITHUB_TOKEN for a higher limit.`
      : '';
    throw new Error(`GitHub API ${response.status} for ${path}: ${message || response.statusText}.${limitHint}`);
  }
  return response.json();
}

async function allPages(path) {
  const records = [];
  for (let page = 1; ; page += 1) {
    const separator = path.includes('?') ? '&' : '?';
    const batch = await github(`${path}${separator}per_page=${PER_PAGE}&page=${page}`);
    if (!Array.isArray(batch)) throw new Error(`Expected a list from GitHub API path ${path}.`);
    records.push(...batch);
    if (batch.length < PER_PAGE) return records;
  }
}

function formatNumber(value) {
  return new Intl.NumberFormat('en-US').format(value);
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB'];
  let value = bytes / 1024;
  let unit = units[0];
  for (let index = 1; index < units.length && value >= 1024; index += 1) {
    value /= 1024;
    unit = units[index];
  }
  return `${value.toFixed(value >= 10 ? 1 : 2)} ${unit}`;
}

async function main() {
  const repository = repositoryFromArguments();
  const encodedRepository = repository.split('/').map(encodeURIComponent).join('/');
  const [repo, releases, issueRecords] = await Promise.all([
    github(`/repos/${encodedRepository}`),
    allPages(`/repos/${encodedRepository}/releases`),
    allPages(`/repos/${encodedRepository}/issues?state=open`),
  ]);

  const openIssues = issueRecords.filter((issue) => !issue.pull_request).length;
  const publishedReleases = releases.filter((release) => !release.draft);
  const totalDownloads = publishedReleases.reduce(
    (releaseTotal, release) => releaseTotal
      + release.assets.reduce((assetTotal, asset) => assetTotal + asset.download_count, 0),
    0,
  );

  console.log(`Bead Grid Studio repository metrics — ${repository}`);
  console.log(`Collected: ${new Date().toISOString()}`);
  console.log('');
  console.log(`Stars:       ${formatNumber(repo.stargazers_count)}`);
  console.log(`Forks:       ${formatNumber(repo.forks_count)}`);
  console.log(`Open issues: ${formatNumber(openIssues)}`);
  console.log(`Releases:    ${formatNumber(publishedReleases.length)}`);
  console.log('');
  console.log('Release assets');

  if (publishedReleases.length === 0) {
    console.log('  No published releases.');
  } else {
    for (const release of publishedReleases) {
      const label = release.name || release.tag_name;
      const releaseDownloads = release.assets.reduce((sum, asset) => sum + asset.download_count, 0);
      console.log(`  ${label} (${formatNumber(releaseDownloads)} downloads)`);
      if (release.assets.length === 0) console.log('    No uploaded assets.');
      for (const asset of release.assets) {
        console.log(`    ${asset.name} — ${formatNumber(asset.download_count)} downloads, ${formatBytes(asset.size)}`);
      }
    }
  }

  console.log('');
  console.log(`Total release asset downloads: ${formatNumber(totalDownloads)}`);
  console.log('Source-code archives generated by GitHub are not release assets and are not counted.');
  console.log('This maintenance script calls GitHub only; it does not run in the web app or track app visitors.');
}

main().catch((error) => {
  console.error(`Metrics failed: ${error.message}`);
  process.exitCode = 1;
});
